[package]
name = "pure_tone"
version = "1.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
eframe = { version = "0.31", default-features = false, features = ["glow", "default_fonts"] }
egui = "0.31"
log = "0.4"

[target.'cfg(not(target_os = "android"))'.dependencies]
eframe = { version = "0.31", default-features = false, features = ["glow", "default_fonts", "wayland", "x11"] }

[target.'cfg(target_os = "android")'.dependencies]
eframe = { version = "0.31", default-features = false, features = ["glow", "default_fonts", "android-native-activity"] }
winit = { version = "0.30", default-features = false, features = ["android-native-activity"] }
android_logger = "0.14"
jni = "0.21"
